"""empty message

Revision ID: 8621be37a780
Revises: 
Create Date: 2023-01-16 18:25:13.417810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8621be37a780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('okta_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionID', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('okta_user')
    # ### end Alembic commands ###
